## AWS CONFIG ##
aws.dynamodb.endpoint=http://localhost:4566
aws.dynamodb.accessKey=test
aws.dynamodb.secretKey=test
aws.region=sa-east-1
aws.profile=localstack

## SERVER PORT ##
server.port=9595

## SPRING CONFIG ##
spring.output.ansi.enabled=ALWAYS
spring.profiles.active=localstack

## DYNAMODB TABLE OVERRIDES (Spring Cloud AWS 3.x) ##
spring.cloud.aws.dynamodb.table-name-overrides[0].entity-class-name=br.com.dynamodb.model.Customer
spring.cloud.aws.dynamodb.table-name-overrides[0].table-name=customers