package br.com.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;

import java.io.Serial;
import java.io.Serializable;

@Builder
@DynamoDBTable(tableName = "customer")
public class Customer implements Serializable {

    @Serial
    private static final long serialVersionUID = -4282005207341771716L;

    @JsonIgnore
    private String id;

    @JsonProperty("company_name")
    private String companyName;

    @JsonProperty("company_document_number")
    private String companyDocumentNumber;

    @JsonProperty("phone_number")
    private String phoneNumber;

    @JsonProperty("create_date")
    private String createDate;

    @JsonProperty("updated_date")
    private String updatedDate;

    @JsonProperty("expiration_date")
    private Long expirationDate;

    @JsonProperty("active")
    private Boolean active;

    public Customer() {
    }

    public Customer(String id, String companyName, String companyDocumentNumber, String phoneNumber, String createDate, String updatedDate, Long expirationDate, Boolean active) {
        this.id = id;
        this.companyName = companyName;
        this.companyDocumentNumber = companyDocumentNumber;
        this.phoneNumber = phoneNumber;
        this.createDate = createDate;
        this.updatedDate = updatedDate;
        this.expirationDate = expirationDate;
        this.active = active;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "company_name")
    public String getCompanyName() {
        return companyName;
    }

    @DynamoDBAttribute(attributeName = "company_document_number")
    public String getCompanyDocumentNumber() {
        return companyDocumentNumber;
    }

    @DynamoDBAttribute(attributeName = "phone_number")
    public String getPhoneNumber() {
        return phoneNumber;
    }

    @DynamoDBAttribute(attributeName = "create_date")
    public String getCreateDate() {
        return createDate;
    }

    @DynamoDBAttribute(attributeName = "updated_date")
    public String getUpdatedDate() {
        return updatedDate;
    }


    @DynamoDBAttribute(attributeName = "expiration_date")
    public Long getExpirationDate() {
        return expirationDate;
    }

    @DynamoDBAttribute(attributeName = "active")
    public Boolean getActive() {
        return active;
    }

}
