name: Coverage Bagde Generator

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Coverage Bagde Generator

    steps:
      - uses: actions/checkout@v4

      - name: Set up the Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'oracle'

      - name: Build with Maven
        run: mvn -B test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: "**/jacoco.csv"

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Flavio Monteiro'
            git config --global user.email 'flaviohnm@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi